include: package:very_good_analysis/analysis_options.yaml
linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    avoid_catches_without_on_clauses: false
    use_setters_to_change_properties: false
    use_if_null_to_convert_nulls_to_bools: false
    document_ignores: false
    one_member_abstracts: false
    missing_whitespace_between_adjacent_strings: false