name: olx_test_runner
description: "CLI tool to help running Flutter tests."
version: 0.10.2
homepage: https://github.com/olxgroup-oss/olx-test-runner
repository: https://github.com/olxgroup-oss/olx-test-runner
issue_tracker: https://github.com/olxgroup-oss/olx-test-runner/issues
documentation: https://olxgroup-oss.github.io/olx-test-runner/
topics: [test, unit-test, cli]
screenshots:
  - description: The OLX Test Runner package logo.
    path: assets/logos/logo_big.png

environment:
  sdk: ">=3.5.4 <4.0.0"

dependencies:
  analyzer: ^7.3.0
  args: ^2.6.0
  cli_launcher: ^0.3.1
  mason_logger: ^0.3.1

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.15
  very_good_analysis: ^7.0.0
